export default [
  'appusers',
  'interfacestandards',
  'bworksparabudgets',
  'bworksstandards',
  'measuremethods',
  'dataloads',
  'budgets',
  'auto-matchers',
  'auto-matcherprobes',
  'bworkssources',
  'loads',
  'bworkssourcegroups',
  'srcconfigs',
];
